### ISSUE TITLE
Random frame skipping when playing 4K video

### ISSUE THREAD

**Issue by z826540272** [CrendKing/avisynth_filter#17]
Random frame skipping when playing 4K video + SVP .
CPU utilization is around 50-60%.

**Comment by CrendKing** [comment]
Frame dropping is usually caused by CPU unable to catch up with the speed of playback. It depends on how fast your CPU can work and how much work you are giving to it. You can either upgrade the hardware, or reduce the the settings in SVP (e.g. instead of tripling the FPS, try doubling see if it improves), or select different parameters (e.g. instead of using 2 threads, try 4 threads etc).

However, if you can identify a particular part of the source code that is not optimal, feel free to suggest a change.

**Comment by z826540272** [comment]
CPU utilization is around 50-60% ,doesnt take up too much，I had a custom script to solve this problem, the secret key is :
Prefetch(6,frames)
parameters ，but it brings another problem, the player randomly freezes when seek . I must close it and reopen it.
So it's not a problem with my computer, it's a problem with the whole playback workflow.

**Comment by CrendKing** [comment]
Have you tried to increase output thread count to 2 or more? It's a hidden setting in registry. SVP should have set it to 1 as default.

You can find the registry key by following https://github.com/CrendKing/avisynth_filter/wiki/How-to-enable-logging. Once you got there, find `OutputThreads` and set to 2 or 3, try again.

**Comment by CrendKing** [comment]
Close due to inactivity.
