### ISSUE TITLE
PotPlayer crashes on playback stop (0.7.5+)

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#25]
... started in https://github.com/CrendKing/avisynth_filter/issues/9#issuecomment-725331263 ...

PotPlayer sometimes crashes with 0.7.5 and later, mostly when switching to another video in playlist and with LAV Video decoder in use. Last lines in the log:
> T   6912 @    33769: Frame handler start BeginFlush()
> T   6912 @    33769: Frame handler cleanup after stop threads

I'm unable to attach debugger to the PotPlayer process for some reason oO so I just tried to narrow the problem down using good-old log file.

The crash occurs while waiting for output thread(s) termination in `t.join();`.
What happens in the output thread? seems like it crashes on `_filter.InitializeOutputSample()`

Interesting fact: 
- I have two more people reporting this
- it doesn't crash on 0.7.4!

> Add a bunch videos to playlist.

It doesn't matter how many videos are in the playlist, just keep switching videos... in fact you don't need a playlist at all, you can just stop-and-play one video 10+ times. Playlist is just a quickest way to do it.

**Comment by chainikdn** [comment]
that one is the reason - https://github.com/CrendKing/avisynth_filter/commit/377be64ddefb74fdea2f4ae011a2be15586e9f2e

**Comment by chainikdn** [comment]
not 101% sure but seems like this fixes it:
```
        IMediaSample* outSamplePtr;
        ATL::CComPtr<IMediaSample> outSample;
        if (FAILED(_filter.InitializeOutputSample(nullptr, &outSamplePtr))) {
            goto BEGIN_OF_DELIVERY;
        }
        outSample.Attach(outSamplePtr);
```

**Comment by CrendKing** [comment]
I managed to cause a crash after many many switches. It is the same problem why I set `outSample` to `nullptr` and added that comment. Turns out `CComPtr` needs a different treatment, which is simply `Detach()`.

Try [AviSynthFilter.zip](https://github.com/CrendKing/avisynth_filter/files/5536659/AviSynthFilter.zip)

**Comment by chainikdn** [comment]
yeah, that seems to work

btw, please check out [these posts](https://www.svp-team.com/forum/viewtopic.php?pid=77115#p77115) by mark007 about frames flickering

**Comment by CrendKing** [comment]
That "flickering" issue seems to be the ghost frames when using ffdshow. I've never seen any of these in avsf. Logically, because we flush all caches during seeking, old frames should never appear.

I'll need full details of how to reproduce with a separate issue. Or if you somehow also see ghost frames, tell me how to do it.

His first issue is https://github.com/CrendKing/avisynth_filter/issues/24, which sounds to be related to particular interlaced video file. I'm still waiting for his sample.
