### ISSUE TITLE
Doesn't pass HDR data w/o the script

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#33]
1. disable SVP
2. open a HDR video -> see BT.709 in madVR's OSD
3. enable SVP -> madVR immediately switches to BT.2020

**Comment by CrendKing** [comment]
The reason of this bug is that when LAV Filters calls `CheckConnect()` on our filter, the media type it presents does not contain the colorspace info (`VIDEOINFOHEADER2::dwControlFlags`). Such information is only passed when it calls `CheckInputType()`. However, our filter currently uses the media type from `CheckConnect()` to generate the output media type. Thus the colorspace info is lost. The side data was correctly sent.

I need to reimplement the pin connection logic with this discovery.

**Comment by CrendKing** [comment]
Verify [AviSynthFilter.zip](https://github.com/CrendKing/avisynth_filter/files/5827336/AviSynthFilter.zip)

**Comment by CrendKing** [comment]
The version above is the bare minimum change. I took some time to further improve the current pin connection logic. Please also verify if you have time.

[AviSynthFilter.zip](https://github.com/CrendKing/avisynth_filter/files/5827689/AviSynthFilter.zip)

**Comment by chainikdn** [comment]
both versions crash when SVP kicks-in. sometimes just hang w/o crashing.
```
An error has occurred. MPC-HC will close now. 
Exception: STACK OVERFLOW
Crashing module: KERNELBASE.dll
```

**Comment by chainikdn** [comment]
ups, sorry, my fault :D

**Comment by CrendKing** [comment]
OK. I was confused because I can't reproduce the crash.

/std:c++latest just allows C++20 features. I use a few of those, such as designated initializer and ranges. I think these features improve code quality and readability.

If you can't build, please do two things:

1. Fresh checkout the repo, and run the build script: `build.bat x64` (for x64 output) or `build.bat x86` (for x86 output). If this works, then something is wrong with your Visual Studio, because the script directly invokes MSBuild. BTW, I also have automatic triggered build in this GitHub repo on every version release. I can manually trigger a build whenever needed. I don't see those builds fail since I switch to /std:c++latest.
2. If the build script also fails with exactly the same message, please post the error messages and your Visual Studio 2019 version. You might need to update VS2019 to latest.
