### ISSUE TITLE
RGB48 doesn't work correctly

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#34]
Consider a 4:4:4 10-bit video (yuv444p10le).
With RGB48 option checked (which is by default) the image is upside-down and with wrong colors. Pin info shows "Connection media type: Video: RGB0 1280x720 23.976fps".
With RGB48 unchecked connection is made with "Video: RGB32 1280x720 23.976fps" and everything works just fine.

**Comment by CrendKing** [comment]
Can't reproduce with my own videos. I need more details. Can you actually use the "Bug report" issue template? Fill as much as you can. Also upload the video somewhere, if copyright is not a concern.

![1](https://user-images.githubusercontent.com/975235/105348804-b3d4e880-5b9d-11eb-8c7d-a975681ae807.jpg)

My video metadata:
```
Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High 4:4:4 Predictive@L3.1
Format settings                : CABAC / 4 Ref Frames
Format settings, CABAC         : Yes
Format settings, Reference fra : 4 frames
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 5 s 0 ms
Bit rate                       : 1 680 kb/s
Width                          : 1 280 pixels
Height                         : 720 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 25.000 FPS
Chroma subsampling             : 4:4:4
Bit depth                      : 10 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.073
Stream size                    : 1.00 MiB (82%)
Writing library                : x264 core 161
Encoding settings              : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=4 / threads=22 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=81 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box        : avcC
```

**Comment by chainikdn** [comment]
- Filter version: https://github.com/CrendKing/avisynth_filter/issues/33#issuecomment-761960159
- AviSynth+ version: 3.5.1
- OS: Win10 x64
- Video player: MPC-HC 1.9.8 64-bit
- Splitter filter and video decoder: built-in LAV
- Video renderer: madVR

https://drive.google.com/file/d/1E8A_3Qz29Rq1FLKGPITSJoPeHQlw1vsE/view?usp=sharing

**Comment by CrendKing** [comment]
I can reproduce now with the script (that's why I ask for the script in the issue template). In fact, the only part matters is `ConvertToYUV420()`. I suspect the upside down is due to the bitmap ordering in Windows API, and wrong color is due to https://github.com/AviSynth/AviSynthPlus/issues/146. I will take closer look at this, but don't have high hope for the wrong color problem since it is due to incompatibility of endian between DirectShow and AviSynth+.

**Comment by chainikdn** [comment]
well, it probably will be better to support yuv 4:4:4 directly

**Comment by CrendKing** [comment]
Like Y410? I could add that if there is demand. Please open an issue for tracking.

**Comment by chainikdn** [comment]
yeah, add a 4:4:4 checkbox, Y410 -> CS_YUV444P16
or just fix the RGB48 bytes order (if this is the reason for the "color problem")
or both :)

**Comment by CrendKing** [comment]
OK. I took a look. Turns out, the "RGB48" in LAV filters is actually [AV_PIX_FMT_RGB48LE](https://github.com/Nevcairiel/LAVFilters/blob/88da52ae317c335929dadc655dda92a709e6b7e8/decoder/LAVVideo/pixconv/convert_generic.cpp#L74), which in ffmpeg is defined as "[packed RGB 16:16:16, 48bpp, 16R, 16G, 16B, the 2-byte value for each R/G/B component is stored as little-endian](https://github.com/FFmpeg/FFmpeg/blob/6dad42854690f5754a1cf1ed138ebd9813e1af37/libavutil/pixfmt.h#L103)". The little endian part is fine, but the component ordering is R-G-B. Unfortunately, AviSynth+ only supports [B-G-R ordering (aka BGR48)](https://github.com/AviSynth/AviSynthPlus/blob/20377502a81eefa9356b04174a12508133ed733e/avs_core/include/avisynth.h#L678).

I made this mistake because the "[RGB32](https://github.com/Nevcairiel/LAVFilters/blob/88da52ae317c335929dadc655dda92a709e6b7e8/decoder/LAVVideo/pixconv/convert_generic.cpp#L56)" and "[RGB24](https://github.com/Nevcairiel/LAVFilters/blob/88da52ae317c335929dadc655dda92a709e6b7e8/decoder/LAVVideo/pixconv/convert_generic.cpp#L60)" from LAV filters are both B-G-R. I blindly assumed their RGB48 would be B-G-R as well.

I created an [issue](https://github.com/Nevcairiel/LAVFilters/issues/391) on LAV filters as petition to support BGR48, but the chance of LAV supporting it is probably not high. As this point, I'll just remove RGB48 option from AVSF as I do not want to implement the costly pixel-by-pixel ordering conversion.

**Comment by CrendKing** [comment]
BTW, normally AVSF only supports formats that are both supported by LAV Filters and AviSynth+. Since Y410 and Y416 are not supported by AviSynth+, the only 4:4:4 format available is YV24, which is only 8 bit.

**Comment by chainikdn** [comment]
well, in this case I'm gonna uncheck everything except 4:2:0 formats at the installation time
"yuv 4:4:4 p10 -> yuv 4:2:0 p16" looks better than "yuv 4:4:4 p10 -> rgb32 -> yuv 4:2:0 p8"

**Comment by CrendKing** [comment]
Or YUV 4:4:4 P10 -> YUV 4:4:4 P8 (YV24) with the latest snapshot.
![1](https://user-images.githubusercontent.com/975235/105476211-353b8200-5c55-11eb-9dfa-fc4a385342d2.jpg)

BTW, Nevcairiel rejected the request to support BGR48, which is totally expected and respected.

**Comment by chainikdn** [comment]
since SVP plugins will only accept 4:2:0, loosing both color resolution and color depth is worse than loosing color resolution only

**Comment by CrendKing** [comment]
> on the other side - "Do not rely on LAV to convert" (c)

We already have LAV (basically ffmpeg) and AviSynth+ in the scene, both of which can do arbitrary conversion. I do not want to mingle another conversion layer in between. If I have to, I'll just convert with ffmpeg swscale.

If you really really want native 4:4:4 P10/16 support, maybe ask AviSynth+ to support Y410/Y416. It will be much easier for them to add one format than me introducing a whole ffmpeg pipeline.

**Comment by CrendKing** [comment]
> Y410 -> planar YUV444 conversion in AVSF

How would this help you? You said SVP only support 4:2:0. So P010/016 is pretty much what you need, which are already supported.

Does SVP support RGB formats (including RGB48LE)? If so, then AviSynth+ supporting RGB48LE would be huge for you. But that's way less likely to happen (than Y410/416).

**Comment by chainikdn** [comment]
> How would this help you?

I'm just saying how it could work in a perfect world.
I'm good with "uncheck everything except 4:2:0 formats at the installation time", as long as this doesn't introduce some other compatibility problem(s). Are we sure LAV will convert _everything_ to YUV4:2:0?

**Comment by CrendKing** [comment]
> Are we sure LAV will convert _everything_ to YUV4:2:0?

That's question for Nevcairiel. Or you can read all the code and judge by yourself ;-)
