### ISSUE TITLE
Green bar on the right side

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#35]
Happens with a non-square-pixel videos (par != 1) (mostly DVD's)
Regression in 0.9.0 - doesn't happen with 0.8.5.

"green" transparent bar - on madVR, and a bw-bar on EVR

**Comment by CrendKing** [comment]
Can you kindly provide a sample video?

**Comment by chainikdn** [comment]
https://drive.google.com/file/d/1j5RPIwy5JUXTBEUe8bYS2RqP_gth1TuN/view?usp=sharing

> happens with minimum script?

doesn't matter

**Comment by CrendKing** [comment]
Hmm, requires account verification? Can you send me a share link in Doom9 PM?

**Comment by chainikdn** [comment]
should work now

**Comment by Disaer** [comment]
Another sample https://fil.email/jHpeWPd4

**Comment by CrendKing** [comment]
Thanks. Found the problematic commit and potential solution. Interesting, all my existing test videos do not manifest this problem. I'll add this one to the "vault".

**Comment by CrendKing** [comment]
Fixed with https://github.com/CrendKing/avisynth_filter/commit/8172dba40cb33afb4fffdfd40d39be461adb83bf

**Comment by chainikdn** [comment]
the title is a bit confusing cause the green bar is also present on 720*480 videos
it's more like "...videos with width not divisible by 32...". but whatever :D
could you probably make a 0.9.1 release?

**Comment by CrendKing** [comment]
> present on 720*480 videos

The two linked videos above have 716 and 854 pixels in width. Both aren't divisible by 16. Can you upload the 720*480 video that has the green bar problem? If that's true, there might be other problems not related to what I found. We surely don't want to release 0.9.1 with that bug still in it. Thanks.

**Comment by chainikdn** [comment]
https://drive.google.com/file/d/1QDCafI18Hslji2wTS2hMHAbT0CXULyGT/view?usp=sharing

**Comment by chainikdn** [comment]
btw, a vertical 1080*1920 one - https://drive.google.com/file/d/1-8WQpHqF2Unl3rJvrws-1lk91IktUPN_/view?usp=sharing - crashes with 0.9.0 but working with 0.8.5

**Comment by CrendKing** [comment]
You are correct. It depends on the YUV compression ratio. For example, in case of 4:1:1, it can trigger even with width not divisible by 16 * 4 = 64. AVSF don't support any 4:1:1 format though. The new logic should have covered all case.

Then it got me thinking, could we simplify the whole (de-)interleave logic more by completely eliminating the inefficient remainder copying? We do that part only because if the buffer size is not big enough, the SSE instruction might over-read or over-write to memory that is outside of the allocated region. But in DirectShow we can control the memory allocation with custom `CMemAllocator` (for upstream) and `DecideBufferSize()` (for downstream). If we always allocate some padding after the actual data, there won't be any memory access violation.

The experimental change and doc for padding can be found at https://github.com/CrendKing/avisynth_filter/commit/618001664e09e55b3b0d0a895c9474e3ed69ec2e#diff-007919e0f4a951ade4617a64cef7d8d19bbc36ddc45e19b53cd945c299385925R69. I tested with all videos I have and works fine. Can you guys test for me?

[AviSynthFilter.zip](https://github.com/CrendKing/avisynth_filter/files/5908593/AviSynthFilter.zip)

**Comment by chainikdn** [comment]
seems to work

**Comment by CrendKing** [comment]
https://github.com/CrendKing/avisynth_filter/releases/tag/v0.9.1
