### ISSUE TITLE
Everything restarted on every track switching

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#54]
Since 0.10 (?).
i.e. the remote control's HWND is changed and SVP thinks the player was closed.
Is it intendent behavior?

**Comment by CrendKing** [comment]
You mean input pin's Inactive() getting called? That's just how DirectShow or MPC-* work. Whenever track is switched, they stop the whole play session then restart. From AVSF's perspective, it's as player pressed the stop button, then play button.

**Comment by chainikdn** [comment]
> how would RC be useful when the player is inactive?

it's not about that
when you stop the RC and DestroyWindow() , SVP think that playback is over and clear everything
just too much of work basically for nothing
RC must be stopped when player is closed OR the video is changed, and it used to work this way before.

**Comment by CrendKing** [comment]
> when player is closed

Like I said, easy to detect by PID.

> video is closed

Like I said, switching track is effectively stopping video.

> video is changed

A DirectShow filter has no idea what video is been played. It just receive streams of samples. So there is no way to tell after a stop and play cycle if the video is changed or not.

For example, a user could very much

1. Play a video
2. Stop the video, but leaving the player open for half an hour, doing something else
3. Close the player process

You are suggesting, in this case, even the video is indeed stopped, we should leave the RC active for the whole time? Because there is no way to tell the difference between switching track and real stopping video.

The only ugly way is "solve" this is, after Inactive(), don't stop RC immediately. Instead, wait for like a minute or so. If still no Active() been called, then stop RC.

**Comment by chainikdn** [comment]
> switching track is effectively stopping video

again, what exactly do you mean by "stopping video"?
if "File -> Close" will delete everything including RC and "Play -> Stop" won't - this looks good to me

**Comment by CrendKing** [comment]
I agree that remote control should only be _disrupted_ at video change/close time, which is at the destructor of the last filter instance (i.e. "filter deleted"). And I think the same goes for the frame handler's worker thread. There is no reason to stop that thread and start a new one when no video is changed/closed.

Please test https://github.com/CrendKing/avisynth_filter/actions/runs/946247582.

**Comment by chainikdn** [comment]
now track switching takes ~10 secs with spamming log with
> Rejecting source sample due to start time going backward
and the source frame number is not reset after switching

**Comment by CrendKing** [comment]
You are correct:

https://github.com/CrendKing/avisynth_filter/actions/runs/946529407 (https://github.com/CrendKing/avisynth_filter/commit/a1a6f692af5d0e4fda3eaa54f3af8954674fd902)

**Comment by chainikdn** [comment]
looks good, thanks
