### ISSUE TITLE
No pictures after starting in fullscreen mode

### ISSUE THREAD

**Issue by ssssssbbb** [CrendKing/avisynth_filter#55]
### Environment
- Filter version: V1.1.2
- AviSynth+ version: 3.5.1
- OS: Win10 x64 1909
- AviSynth script: SVP4.5.206
- Renderer: Madvr 0.92.17
- Decoder: LAV video decoder 0.75
- Log file link
[june20.log](https://github.com/CrendKing/avisynth_filter/files/6681796/june20.log)

### Describe the bug
First press enter in PotPlayer, than press space to start a new playing of this run(not from pause), there is no picture, but audio is normal.
Enter fullscreen during playing is normal.

### To Reproduce

1.AVSF+Madvr+SVP or AVSF+Madvr without SVP: no picture, black screen
2.AVSF+EVR+SVP or AVSF+EVR without SVP: normal
3.FFdshow raw filter: normal
4.no filter: normal
5.MPC-HC: can't enter fullscreen before start playing
6.AVSF+Madvr+SVP with Potplayer's exclusive mode(fast):Potplayer not responding
[pot exclusive.log](https://github.com/CrendKing/avisynth_filter/files/6681819/pot.exclusive.log)
7.AVSF+Madvr+SVP with Potplayer's exclusive mode(slow): no picture, black screen
8.AVSF+Madvr+SVP with both Potplayer and Madvrs' exclusive mode: no picture, black screen

Is this a bug?

**Comment by CrendKing** [comment]
Again, is it on specific video or all? And madVR only? What if after start you enter fullscreen?

Though MPC-HC can't, [MPC-BE](https://sourceforge.net/projects/mpcbe/) can. If you can reproduce this issue on MPC-BE, that would be very helpful.

**Comment by ssssssbbb** [comment]
It's on all videos, madVR only. Entering fullscreen after start is OK.

MPC-BE is OK. But I did find something. I found videos on MPC-BE are somehow sharper? can't figure out the exact differences, so I serached online and found someone said it's due to the "output color space" in POT settings. I followed and set it to RGB32 instead of "auto", and... it's just solved, no black screen anymore. I didn't dig into the video quality problem, forget it.

I also tested the freezing problem with this color space setting but found nothing different.

**Comment by CrendKing** [comment]
According to my test, the "output colorspace" is basically the output format of the PotPlayer's built-in video decoder and transformer, before it connects to AVSF. So if you DON'T use LAV Video Decoder, and e.g. set it to P010, regardless of what video you play, AVSF always takes P010 as input. But according to your log, you do use LAV VD, so that setting should have absolutely no use. Can you confirm the format is indeed changed to RGB32? A log suffices. Or you can check it in the Pot OSD (press Tab), or check with madVR OSD.

**Comment by ssssssbbb** [comment]
Yes, it should be absolutely no use, I forgot this.

Forget it...that's occoasionly and not rigorous. I did more test and found it's related to the position where I started. In some positions I can always get pictures if the time point is restrictly right. And it's on all videos, I can't figure out the difference.

**Comment by ssssssbbb** [comment]
Maybe I should just give up PotPlayer...

**Comment by CrendKing** [comment]
Since I do not experience these issues when I use PotPlayer, maybe you could try MPC-HC/BE or even mpv for a while, see if the same problems eventually surface there as well. If so, then we can conclude something is wrong with e.g. your environment, or madVR settings, video card driver, etc. If not, then you find a working player to use. Either way we achieve something.

**Comment by ssssssbbb** [comment]
MPC-HC is out of date. MPC-BE can't store the last playing progress. MPV... it doesn't have UI?

Maybe I will try VLC but it seems to be not working with MadVR?

By the way, what are you using? Are you not using PotPlayer? I tried Vapoursynth R53 but it doesn't work. Can't it work with PotPlayer? I can't even enter the configuration window since the earlier version. I updated my SVP to 4.5.210 and I'm sure that the vapoursynth.dll is reachable (tried installing or put it into system32).
![1](https://user-images.githubusercontent.com/82156140/122678144-0cc1af00-d218-11eb-9e89-85e1e2410859.jpg)

**Comment by CrendKing** [comment]
[clisd2's MPC-HC](https://github.com/clsid2/mpc-hc/releases) is not out of date. Last release was 15 days ago. MPC-BE can store last playing progress: Options -> Player -> Remember File position. And mpv:

1. the original indeed doesn't have UI, but there are so many modified version that add UI: [mpv.net](https://github.com/stax76/mpv.net), [SMPlayer](https://www.smplayer.info/). Here is an (out of date?) list: https://github.com/mpv-player/mpv/wiki/Applications-using-mpv#gui-frontends
2. mpv is extremely customizable. It allow users to write there own script to control every aspect of the player. So in a sense UI is not always necessary. For example, instead of using context menu to rotate video, you could assign a keyboard shortcut to do that. Or you could even write script to detect videos that need rotation and automatically do so. Now, I'm not saying this approach is for everyone, but if you are a hacker, mpv is actually the best.

VLC doesn't support madVR. And neither can mpv. The question is, do you really really need madVR? If you play a video in mpv/VLC and in PotPlayer w/ madVR, where both are fully optimized to your need (e.g. best suited vo, scaling algorithms, shaders, etc), do you still find noticeable difference between them? If not, or if the former is "good enough", ask yourself if you are willing to trade.

> Can't it work with PotPlayer

Both variant of this filter work in PotPlayer. You might have installation problem.

**Comment by ssssssbbb** [comment]
That option of MPC-BE can only store the last file, not the progress, I've checked it bufore I start playing.

I thought it's definately not necessary to use madVR before, but after I tried it on 720P and some webrip 1080P videos, I think it's good, visuablly sharper. But yes, maybe mpv/VLC is better or worth trading.

I've read the closed issue and found I got the wrong dll, it should be VSScript.dll, I'll try again.

**Comment by CrendKing** [comment]
I'm very positive (just tested) that MPC-BE AND MPC-HC's "Remember file position" store the last n played file's progress, where n is the configurable "number of recent files". There is a whole section in the config file for that functionality (`RecentFiles`). BTW, for mpv, there's also (lua script)[https://github.com/hacel/recent] to do the same thing. You can write your own too.

For madVR, I agree that if I'm using MPC-XX or Pot, madVR is no-brainer upgrade. But think about: it is basically a video renderer with some high quality scaling and enhancement algorithms, and handles 10-bit and HDR videos. Can mpv do the same? Yes. It supports glsl shaders so things like [FSRCNN](https://github.com/igv/FSRCNN-TensorFlow) and [KrigBilateral](https://gist.github.com/igv/a015fc885d5c22e6891820ad89555637) provides the same functionality, except they are all open source so you can pick and choose which you like. Of course, the trade off is you need to do some research.

**Comment by ssssssbbb** [comment]
OK, maybe I mixed up on/off with that option.

MPC-BE can't enlarge the toolbar icons while MPC-HC can, it will be my backup.

Vapoursynth Filter works with no #47 problem, but #55 problem still exists. The failure was because my "PATH" environment varible had too many duplicated items (don't know why, maybe caused by the VC2005-2019 runtime pack), out of 2047 bytes, so the installation couldn't add something into it. But... it has poor performance, it sutters when speeding up and meantime I can see the madVR decoder queue, upload queue, presant queue and render queue droping till 1/24 and 1/8.

**Comment by CrendKing** [comment]
Sorry for the digress. So if MPC-BE does not have problem when starting from fullscreen while PotPlayer does, I think it could be PotPlayer related. But I don't know what since the log shows frames were generated and delivered. Could be the interaction between player and madVR.

VapourSynth variant should have at least the same, if not better, performance than AviSynth variant, with less memory footprint. The fact you have performance issue worth a separate issue, but please confirm the same issue in MPC-XX first. If it's specifically tied to PotPlayer, please note it in the report.

**Comment by ssssssbbb** [comment]
Yes, you're right.
