### ISSUE TITLE
MPC-BE crashed on start up when playing media file

### ISSUE THREAD

**Issue by aloola18** [CrendKing/avisynth_filter#58]
my mpc-be crashed when I play file in the folder with the name:

【MMD】MAMAMOO - gogobebe

turning off AVSF and I can play the file normally. 
avsf ver 1.1.6

I use the plugin with SVP.

**Comment by CrendKing** [comment]
Are you suggesting if you change the folder name without changing anything else, it would not crash? Can you provide log?

**Comment by aloola18** [comment]
changing only the folder name and it wouldn't crash anymore. 
https://cdn.discordapp.com/attachments/290709370600423424/863724065922744330/mpc-be64.exe.1.5.8.6302.dmp here is the dump file

The video file https://1drv.ms/u/s!AvZFs4-QK6gCgYsmrBQhhHXcCKX5QA?e=jranas

**Comment by CrendKing** [comment]
The root cause is basically a problem in AviSynthPlus that can't handle Unicode character in file path, described in https://developercommunity.visualstudio.com/t/stdfilesystempathgeneric-string-throws-an-exceptio/721120. This problem only happens when using AVSF and MPC-BE because MPC-HC would instead set current directory to it's executable's folder. There is nothing I can do.

You can do two things:
1) Open an issue to AviSynthPlus to suggest them handling these Unicode characters in their future versions. However, since SVP can't use any AVS+ version beyond 3.5.1 right now, it won't solve your problem.
2) Switch to the VapourSynth variant (which is already supported by SVP).

Of course, you can also rename the video directory.
