### ISSUE TITLE
Interlaced flag (?) after AVSF

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#59]
MPC-BE, EVR-CP, LAV decoder, sw decoder, no SVP
AVI file containing progressive Xvid 704x528 29.97fps stream.
https://drive.google.com/file/d/1qTV5lPS-uWZgAIDRjSN5eeleotB69teo/view?usp=sharing

Playing w/o AVSF: first two lines in renderer stats:
> Frame rate: 29.980 (...)
> Frame type: Progressive

Playing with AVSF:
> Frame rate: 59.980 (...)
> Frame type: Interlaced : Bottom fields first

Probably related to #53 ?

Other user said it started after 0.9.4.

**Comment by CrendKing** [comment]
Here's the thing. MPC-BE has this function in IPinHook.cpp:
```
static HRESULT STDMETHODCALLTYPE ReceiveMineI(IMemInputPinC * This, IMediaSample *pSample)
{
	if (pSample) {
		// Get frame type
		if (CComQIPtr<IMediaSample2> pMS2 = pSample) {
			AM_SAMPLE2_PROPERTIES props;
			if (SUCCEEDED(pMS2->GetProperties(sizeof(props), (BYTE*)&props))) {
				g_nFrameType = PICT_BOTTOM_FIELD;
				if (props.dwTypeSpecificFlags & AM_VIDEO_FLAG_WEAVE) {
					g_nFrameType = PICT_FRAME;
				} else if (props.dwTypeSpecificFlags & AM_VIDEO_FLAG_FIELD1FIRST) {
					g_nFrameType = PICT_TOP_FIELD;
				}
			}
		}
	}

	return ReceiveOrg(This, pSample);
}
```
So it defaults to bottom field interlaced unless it finds `AM_VIDEO_FLAG_WEAVE` in the AM_SAMPLE2_PROPERTIES::dwTypeSpecificFlags field. When AVSF receives the input sample from upstream, it never cared about that field. So on the output side, that flags got lost.

On the other hand, MPC-HC's approach to detect interlaced is [checking VIDEOINFOHEADER2::dwInterlaceFlags](https://github.com/clsid2/mpc-hc/blob/29a1254b5d4cadd3916b3ae4d3456bc3410af213/src/filters/renderer/VideoRenderers/EVRAllocatorPresenter.cpp#L1613), which we do carry over to the output side. So the result stats in MPC-HC is correct.

I'm leaning towards not fixing and hoping MPC-BE one day switches to use dwInterlaceFlags. Because saving and restoring per-sample properties is time consuming, while it seems to be purely cosmetic and not causing any rendering issue. If there is actual damage of not setting the properties, please let me know and I'll reconsider.

**Comment by chainikdn** [comment]
Sounds odd. If you have some flag on input, why not keeping it on output? :/

**Comment by CrendKing** [comment]
I think the dwTypeSpecificFlags field is redundant information. You already have the interlaced flags in media type. If the sample has exactly same information, why exist in both places? If they differ, which is the source of truth? The doc says "Type-specific flags", not "Sample-specific flags". So all I'm saying is I'm picking the media type as the source of truth and ignoring the other, because media type applies to all samples until type change, which is more performant.

I can't guarantee anything that I don't control. If a player has some unwanted behavior, we can discuss and figure out solution. If not, I think status-quo is acceptable atm.

**Comment by chainikdn** [comment]
> I think the dwTypeSpecificFlags field is redundant information

so what? you can argue with Microsoft about it ;)
but do you really want to decide which one must someone use? is it forbidden by the docs to use dwTypeSpecificFlags? I believe no.

**Comment by CrendKing** [comment]
Fine: https://github.com/CrendKing/avisynth_filter/actions/runs/1043412908

**Comment by CrendKing** [comment]
In released v1.2.0, I made some changes to the implementation above. See the [release note](https://github.com/CrendKing/avisynth_filter/releases/tag/v1.2.0) for detail.

**Comment by chainikdn** [comment]
I'm afraid there's a memory leak appeared after this commit. At least build from 19/07 is already "infected".
SVP is off, MPC-HC, start playback, seek several times, **switch to the next file in playlist**, seek again --> observe +100-200 MB memory usage with every seek.

**Comment by CrendKing** [comment]
Yes. The bug is introduced [here](https://github.com/CrendKing/avisynth_filter/commit/03f102339912864a9f57713152213c2af463cd1b#diff-842616413cb58bef863a7462c998bb1713cf91e5c2c1fdae479f1b2672b3b0adL232). The lambda captures `this`, which is the entire FrameHandler, while being static. So even switching video (which re-initialize the whole filter) will not destroy that instance.

https://github.com/CrendKing/avisynth_filter/commit/ae63b616dbe5bc7c3e0031f3c121dd88c0c6b424 should fix this.
