### ISSUE TITLE
d3d11 direct-mode breaks when remote control is enabled

### ISSUE THREAD

**Issue by sofakng** [CrendKing/avisynth_filter#72]
This is regarding issue #63.

@CrendKing It looks like when I [Enable Remote Control] in AviSynthFilter it stops using direct mode.  It doesn't matter if any scripts are running;  simply enabling the remote control breaks it.

Here are my logs:
[avisynth_filter_no-remote.log](https://github.com/CrendKing/avisynth_filter/files/8577409/avisynth_filter_no-remote.log) (d3d11 cb direct)
[avisynth_filter-remote.log](https://github.com/CrendKing/avisynth_filter/files/8577410/avisynth_filter-remote.log) (d3d11 cb)

Strangely, the log file when remote control is enabled is quite large compared to the non-remote control?

The reason this is a big deal is because when direct mode is enabled, my 6K-8K videos playback fantastic.  However, once direct mode is removed they are extremely choppy.  Sometimes they will become smooth for a few seconds but then go back to choppy.

**Comment by CrendKing** [comment]
If you don't have any script, when remote is also disabled, AVSF automatically unloads itself, making LAV directly connects to the renderer. That's why the log is small, and LAV is able to use "d3d11 native" mode.

When remote is enabled, AVSF won't unload itself. LAV will connect to AVSF first, which is connected to the renderer. And all AviSynth/VapourSynth things work in CPU, so LAV has to copy frames from GPU to main memory, thus "d3d11 cb direct" mode.

If you want to use this filter, you have to suffer that memory copy penalty. If you hardware can't support 8K without copyless mode, then you might want to consider disabling AVSF, or write a script that conditionally unload based on video resolution.

**Comment by sofakng** [comment]
Thanks for the explanation and that explains what is happening.

However, when AVSF is connected shouldn't it be using d3d11 cb direct?  (that was the issue from #63)

Also, do you have any idea what memory speed/requirement I would need for larger video files like these?

**Comment by CrendKing** [comment]
It is d3d11 cb direct in my end:

![Clipboard 1](https://user-images.githubusercontent.com/975235/165652303-2f7b9e29-caea-46ba-b114-70975349aeaa.jpg)

> Also, do you have any idea what memory speed/requirement I would need for larger video files like these?
I have no idea. Everyone's hardware, software and script are different.

**Comment by sofakng** [comment]
You are seeing d3d11 cb direct with Remote Control enabled?

**Comment by CrendKing** [comment]
> You are seeing d3d11 cb direct with Remote Control enabled?

Yes. It doesn't matter because RC does not affect anything in terms of format during pin connection. The earliest time external app such as SVP can inject is when [the input pin becomes active](https://github.com/CrendKing/avisynth_filter/blob/master/filter_common/src/input_pin.cpp#L83).

> Benchmark

I'm not sure what you are trying to achieve. Do you have a particular script you think is slowing down the process? If so, replace it with a no-op script and try again. If then it becomes OK, you know the script needs change. If still bad, then bottleneck is AVSF/VPSF. Then we can talk about the performance issue in the filter. We can profile the process to see where most the resource is spent on.

**Comment by CrendKing** [comment]
Thanks for the video. It is the culprit of why you are only seeing "cb" while I'm seeing "cb direct".

Since issue #63 I know that LAV enables the "direct" mode if the media sample's stride is multiple of 16 or 32, depending on format. If the video's width happens to be a multiple of that number, then by doing nothing we got the direct mode. For example, my test video is 1280x720, where 1280 is multiple of 16. Your video is 5800x2900, where 5800 is NOT multiple of 16.

Previously AVSF has no negotiation logic to align the stride, so the stride is always the same as the width of the video. https://github.com/CrendKing/avisynth_filter/actions/runs/2238748253 is a test build that always aligns stride to 32. So you should always have "cb direct" mode now.

The second problem you mentioned, where if you enable RC without any script the performance is poor, is caused by a combination of how AviSynth works, and how AVSF's RC works. Basically in AVSF, RC enabled + no script is equivalent to use a script as follows:
```
AvsFilterSource()
```
As you may notice, there is no `Prefetch()` here. Due to the single threaded nature of AviSynth, without prefetcher the performance on large video will suffer significantly. On the other hand, VapourSynth's API is mainly async, therefore if you do the same thing on VPSF you won't see any performance issue.

You may ask why I do not add `Prefetch()` in this case. The reason is that RC is mainly used for external apps to inject their script at early stage, and the injected script should have its own `Prefetch()` statement.

If you have a valid use case where injection happens conditionally, or late into playback, please let me know, I'll reconsider the design.

**Comment by CrendKing** [comment]
> it crashes

I can't reproduce a crash. Please upload your [log](https://github.com/CrendKing/avisynth_filter/wiki/How-to-enable-logging).

> which I guess is expected

No. I updated the filter so you don't need to do anything and always have the direct mode enabled.

> a performance problem elsewhere on my system

How much CPU usage you are seeing? If it is already close to 100%, then your system can't handle this. However, I have a Ryzen 5800X, that two line only costed me like 15%. So it shouldn't be that bad, unless your CPU is very old.

**Comment by sofakng** [comment]
OK - Here is my log file:  [avisynth_filter.log](https://github.com/CrendKing/avisynth_filter/files/8587563/avisynth_filter.log)

I'm using MPC-HC:
![image](https://user-images.githubusercontent.com/2228499/165871818-a023c33a-9b7d-4fcc-82ea-a6e67c833e50.png)

When I start playing a video with remote control enabled (but no script specified), MPC-HC crashes and it uploads this dump file:  https://drdump.com/UploadedReport.aspx?DumpID=95836898

**Comment by CrendKing** [comment]
Gotcha. It is due to your AviSynth+ version being 3.5. Recently I changed to call a function that only exists in 3.7 because the old one is deprecated. Can you try 3.7.2?

**Comment by sofakng** [comment]
I think you've solved it.  Upgrading to AviSynth+ v3.7.2 fixed the crash and also enabled direct mode.  The stutters are now basically gone except for about a 0.5 second stutter when seeking.

One last question before this is closed --

You mentioned that LAV filters automatically enabled direct-mode if the resolution was a multiple of 16 or 32 but this changed it to always use a stride of 32 so it will work with all videos in the future regardless of the resolution being a multiple of 16 or 32?

**Comment by CrendKing** [comment]
0.5 second stutter is ideal but also not very bad on such large video. You could also try the VapourSynth variant, could be better. Still, if you don't have anything to do with the filter (e.g. not use SVP, not use mvtools, etc.) you don't need to use this filter at all.

To your question: yes. Old code requires video width to be multiple. New code does not. It will automatically adapt.

Reopen if needed.
