### ISSUE TITLE
Video freezing while switching subtitles

### ISSUE THREAD

**Issue by chainikdn** [CrendKing/avisynth_filter#76]
Regression in ver. 1.4.1.
Switch between subtitles -- notice video freezing from several seconds to forever.
Environment: MPC-HC, madVR, AVSF, no script, no SVP.
For me this only happens with MPC-HC+madVR, doesn't happen with other renderers (EVR, MPC) or other players (MPC-BE, PotPlayer). However another user said "it also freezes on other renderers".

**Comment by CrendKing** [comment]
I tried all combinations below on latest version and can't repro
* MPC-HC / MPC-BE
* madVR / EVR
* Internal / External subtitles
* Even tried switch audio tracks

When you say "Regression in ver. 1.4.1." do you mean it only happens in 1.4.1 and not 1.4.2 and 1.4.3, or since 1.4.1?

Also, I probably need a video to help repro.

**Comment by chainikdn** [comment]
> or since 1.4.1?

this

> I probably need a video to help repro.
https://www.svp-team.com/forum/viewtopic.php?pid=80667#p80667
https://www.youtube.com/watch?v=leq8ov-iaD0

**Comment by CrendKing** [comment]
Tried so many times, and only managed to "freeze" for 1 second, twice. Seems extremely rare, and only happens for the remote injection scenario. Never happens with fixed script.

Probably need a more reliable way to repro to handle this issue.

**Comment by chainikdn** [comment]
>  only happens for the remote injection scenario. Never happens with fixed script.

>> no script, no SVP

**Comment by CrendKing** [comment]
I tried the exact same setup and can't reproduce. There is always slight freeze when switching tracks, because that's basically equivalent to re-opening the video file. However, there shouldn't be a difference between remote injection vs fixed script. They go through the same process. Would you please upload log of the those two scenarios?

**Comment by Skaitliuk** [comment]
> Would you please upload log of the those two scenarios?

I don't really understand how this works and what scenarios you need. I uploaded log with filter version 1.4.3 and no SVP running (when freezes happen), 1.4.3 with SVP running and 1.3.1 no SVP. Is this what you wanted? each time I start the same video and cycle through subtitles ~8 times.

[1.3.1 no svp running.log](https://github.com/CrendKing/avisynth_filter/files/9039753/1.3.1.no.svp.running.log)
[1.4.3 no  SVP running.log](https://github.com/CrendKing/avisynth_filter/files/9039755/1.4.3.no.SVP.running.log)
[1.4.3 SVP running.log](https://github.com/CrendKing/avisynth_filter/files/9039756/1.4.3.SVP.running.log)

**Comment by CrendKing** [comment]
The second log shows lots of message about "Rejecting source sample due to start time going backward". I'm theorizing that you are facing a race condition that I can reproduce locally, which is the usual nature of race condition.

That race condition exists because I deliberately chose to not lock most of `AddInputSample()` exclusively for performance concern. However, if it is the case of this bug, we may have to sacrifice that bit of performance for correctness.

Please test https://github.com/CrendKing/avisynth_filter/actions/runs/2768521271. If it indeed fixes your problem, we can discuss about performance.

**Comment by Skaitliuk** [comment]
The freezes are gone for me. Logs attached just in case.
[avisynth_filter.log](https://github.com/CrendKing/avisynth_filter/files/9229518/avisynth_filter.log)

**Comment by CrendKing** [comment]
Thanks. I optimized the logic a bit. Could you please test this?

https://github.com/CrendKing/avisynth_filter/actions/runs/2831024679

**Comment by Skaitliuk** [comment]
Freezes are back again when switching subtitles. 
[avisynth_filter.log](https://github.com/CrendKing/avisynth_filter/files/9299601/avisynth_filter.log)

**Comment by CrendKing** [comment]
I think I found the root cause. Hope https://github.com/CrendKing/avisynth_filter/actions/runs/2845275349 fixes for real.

**Comment by Skaitliuk** [comment]
yes, subtitles freezes are gone, but now MPC-HC freezes(not responding) on video seek.
With MPC renderer, MPC-HC freezes on the first video time seek;
With MadVR, freezes when I seek a paused video....
[avisynth_filter.log](https://github.com/CrendKing/avisynth_filter/files/9320863/avisynth_filter.log)

**Comment by CrendKing** [comment]
Sorry, I forgot to test the change on some video renderers, such as EVR and MPC. Fix: https://github.com/CrendKing/avisynth_filter/actions/runs/2850151566

**Comment by Skaitliuk** [comment]
No more issues from me, everything works, thank you

**Comment by ssssssbbb** [comment]
Potplayer with madVR renderer freezes on immediate seek after start playing, EVR(CP) is OK, and MPC-HC is OK with both renderers.

This version is good, https://github.com/CrendKing/avisynth_filter/actions/runs/2831024679, later ones are not.

**Comment by CrendKing** [comment]
I can't reproduce the issue, and I can't find anything extraordinary from your log. Again, even if I can repro, there is not much I can do, as both PotPlayer and madVR are closed source.
