### ISSUE TITLE
Some videos are broken with avisynth_filter

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [CrendKing/avisynth_filter#77]
When I activate Avisynth plus in potplayer as
![изображение](https://user-images.githubusercontent.com/4449851/181714778-34b35af7-f82b-4a27-add5-13cb23ba1307.png)
![изображение](https://user-images.githubusercontent.com/4449851/181714831-9aaea17f-9c45-4132-b5ec-91fdbfaac4c1.png)

i get this:
https://media.discordapp.net/attachments/810211316794916925/997197258443473016/Harder_Neco_Faster_Arc..mp4

![изображение](https://user-images.githubusercontent.com/4449851/181718975-b18acd48-a403-4e91-bfa7-5c935af77030.png)

https://files.catbox.moe/zdtn9y.mp4

![изображение](https://user-images.githubusercontent.com/4449851/181719142-e8c3e283-0452-4080-9508-84228e78c689.png)

SVP version is also broken.
But internal potplayer avisynth processing is ok.

**Comment by CrendKing** [comment]
Tested both videos and works fine here. Please upload some log.

**Comment by 0x4E69676874466F78** [comment]
@CrendKing
[avisynth_filter.zip](https://github.com/CrendKing/avisynth_filter/files/9228458/avisynth_filter.zip)

**Comment by 0x4E69676874466F78** [comment]
I noticed that sometimes the video plays correctly. Could there be timing issues here?

**Comment by 0x4E69676874466F78** [comment]
In MPC-HC everything works fine. The problem is only on Potplayer.

**Comment by 0x4E69676874466F78** [comment]
![изображение](https://user-images.githubusercontent.com/4449851/182021902-e8660e02-37c7-41cb-ac97-dabf490da818.png)

**Comment by 0x4E69676874466F78** [comment]
More and more oddities.
It seems to be related to DXVA and video resizing (if DXVA disabled then PrBoom video works fine, but not neco video)
BUT!
Right click on video -> Video -> Resize -> Do nothing = bug.
Resize -> Resize always (or another modes) = works fine for all videos (even when DXVA enabled). 
Restart player required.

**Comment by CrendKing** [comment]
I can repro now, thanks to the log. It looks like you are not using LAV Filters to decode the video, but rather relying on PotPlayer's builtin filters. That somehow caused the problem. The reason why MPC-HC works is that it comes with LAV.

I mainly test the code with MPC and LAV, simply because they are open source. If you are not using the combination, expect to run into issues. Even if I want to support PotPlayer, they actively reject debugger to attach, and being closed source is not helping.

Since you can easily workaround by just using LAV in PotPlayer, I tend to close this as won't fix. Is it OK?

**Comment by 0x4E69676874466F78** [comment]
@CrendKing yes LAV Filters with decoding (which includes FFDShow video decoder) works correctly.

**Comment by 0x4E69676874466F78** [comment]
I think this issue is worth mentioning in the readme.

**Comment by CrendKing** [comment]
> I think this issue is worth mentioning in the readme.

Sure. Do note that not all videos has the issue. Given you are the first person reporting this, it's probably rare.
