### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by flossy83** [CrendKing/avisynth_filter#79]
### Environment
- Filter version: current version
- Renderer version: MadVR current version
- AviSynth+ version: current version
- OS: Windows 7 x64
- AviSynth script: just AvsFilterSource()

### Describe the bug
Aspect ratio of a 720x576 square pixel video is slightly squashed from 1.25:1 → 1.22:1 (test clip in last section)

### To Reproduce
https://forum.doom9.org/showthread.php?p=1977687#post1977687

**Comment by CrendKing** [comment]
Could you please move the feature request to a separate issue for better tracking?

**Comment by flossy83** [comment]
Thank you, that seems to have resolved it. 

But there is still a problem slightly related to this -- a lot of my scripts perform custom cropping and scaling which assumes square pixels for all videos, since that is how standalone Avisynth normally behaves.

But with your plugin forwarding on DAR metadata to the renderer, this breaks those scripts since the renderer no longer thinks it's getting square pixels.  

Is it possible to have an option to disable all DAR processing in your Avisynth filter and just treat all videos as square pixels?

**Comment by flossy83** [comment]
Actually, if I set manually _SARNum & _SARDen to 1 & 1 in my script, will Avisynth pass that on to renderer, or are there some edge cases where Avisynth filter will force a particular value?

**Comment by CrendKing** [comment]
> DAR metadata to the renderer

I'm not sure if I get your concern correctly. DAR is part of `VIDEOINFOHEADER2`, which all filters preserves, including LAV Filters.

On the other than, since you mentioned "square" pixels, I assume you are actually talking about pixel aspect ratio (PAR), not display aspect ratio (DAR)? AFAIK, feel free to correct me if I'm wrong here, there is metadata in DirectShow that sets PAR directly. According to [wiki](https://en.wikipedia.org/wiki/Pixel_aspect_ratio#Introduction), PAR = DAR / SAR (SAR being **storage** aspect ratio here). Since we have both DAR and SAR, we can always calculate PAR. Our filters already calculate PAR and set `_SARNUM` and `_SARDen` properties (SAR being [**sample** aspect ratio](http://www.vapoursynth.com/doc/apireference.html#reserved-frame-properties), which is the same as PAR) VPSF shows the SAR for this particular video being 1, as shown below.

![Clipboard 1](https://user-images.githubusercontent.com/975235/200848340-385e000c-02e6-4a7d-82ec-ca70d9fa5d07.jpg)

What I changed in https://github.com/CrendKing/avisynth_filter/commit/62a7cc56a44ebca36133bb543f3fe2babe5bbc2a is fix the calculation so that if synth script does any crop or resize to change video dimension, we preserve the original PAR (usually being 1:1), and update DAR in VIH2.

If it is broken for your script, could you post a dumb-down version of your script, test video and expected/actual result so I can repro?

**Comment by CrendKing** [comment]
Oh, forgot to mention that I also fixed the unsimplified SAR numbers. The previous 2880:2880 should be now 1:1.

**Comment by flossy83** [comment]
The problem is that normally when we use Avisynth on its own without your Directshow filter there is no Directshow metadata like dwPictAspectRatioX/Y being passed through to the renderer.   eg. for a 720x576 16:9 video we have to manually stretch this in Avisynth like eg. BicubicResize(1024, 576) to get the correct aspect (1024/576 = 16/9) otherwise the aspect would be 720/576=1.25.   That test pattern is an outlier that just happens to be natively 720x576 1.25:1 but no video exists like that in the real world.     

Test clip 720x576 16:9
https://drive.google.com/file/d/1inJLUTbTf01YRCVBqENdoc-gjXL05soy/view?usp=share_link)

Standalone Avisynth (just opening my .avs file directly in MPC-HC without your filter enabled) 
https://i.ibb.co/BrbrM17/1.png

Avisynth Filter (opening the mkv in MPC-HC with your filter enabled)
https://i.ibb.co/WF3yRvm/2.png

It's actually a very good thing that your filter passes the metadata through, it's just that it's causing this inadvertent issue where we have to re-do all our aspect handling in our scripts.

I guess I'm looking for a way to force Avisynth filter to behave as if dwPictAspectRatioX/Y is null or not set?

**Comment by flossy83** [comment]
Initially I was using standalone Avisynth with DirectShowSource() as the source filter, which uses LAV Video decoder as that happens to have highest merit on my system.   In this configuration I get square pixels -- it appears the source filter doesn't pass any AR flags to renderer.    Same result with FFmpegSource2() and LWLibavvideosource() but they don't use DirectShow.

In MPC-HC, unticking "Internal filters > Avisynth" uses Windows own generic AVI splitter ("AVI/WAV File Source") as that happens to have highest merit on my system.   (otherwise it uses MPC-HC's internal LAV splitter).   Again square pixels.

Rendering Avisynth scripts to h.265 and h.265 files using ffmpeg: square pixels.

Purely for the sake of backwards compatibility, it would be nice if we force square pixels with something like: 

`propSet("_SARNum", last.width)`
`propSet("_SARDen", last.height)`

(these should really be called _PARNum and _PARDen -- Avisynth wiki says they are "[Pixel (sample) aspect ratio](http://avisynth.nl/index.php/Internal_functions#SARDen)".  


> What's the "interference" in the screenshot?

The edges are cropped off.  The second overlay is MadVR's debug screen which thinks it's still receiving 720x576 16:9 from Avisynth filter.

Also keep in mind in Avisynth we are doing all kinds of crazy things like SeparateFields(), SelectEven(), nnedi3() upscale field 1 to double height etc. etc. and all this has to be handled the same geometry which might get interfered with if Avisynth filter is performing its own adjustments behind the scenes but I haven't tested this yet, maybe it works perfectly and it's only the final scale that gets affected by the dwPictAspectRatioXY flags.
