### ISSUE TITLE
AviSynthPlus-RIFE colorspace errors

### ISSUE THREAD

**Issue by Usulyre** [CrendKing/avisynth_filter#83]
### Environment
- Filter version: 1.4.5
- AviSynth+ version: 3.7.3 (r3689 x86_64)
 MPC-BE x64 1.5.8
- OS: [Windows 11 x64]
- AviSynth script: [

AvsFilterSource()

ConvertBits(32, fulls=false, fulld=true)
ConvertToPlanarRGB(matrix="pc709", chromaresample="spline36") # change matrix if it's other

RIFE(model=23, factor_num=2, factor_den=1, gpu_id=0, gpu_thread=8)

### Describe the bug
Getting a colorspace error : Convertbits: YUV2 input must stay in 8 bits

**Comment by CrendKing** [comment]
Have you tried to follow the message and convert the 16-bit video to 8-bit?

**Comment by Usulyre** [comment]
How do I do that? Sorry I couldn't figure it out yet. I was following this issue:

https://github.com/Asd-g/AviSynthPlus-RIFE/issues/1

**Comment by CrendKing** [comment]
I tried the plugin. The script you quoted is correct but incomplete, because the output of `RIFE()` seems to be the same as output, which is planar RGB 32. This is a format not supported by DirectShow, you need to convert it back to something like YV12, such as
```
ConvertBits(8)
ConvertToYV12()
```
Unfortunately, it seems there are other issues in the plugin, which always causes my player to crash with "ACCESS VIOLATION" error.

Please follow up with the plugin author to address these problems.
